/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package banker.review;

import java.io.OutputStreamWriter;
import java.io.PrintWriter;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;

import ConnectionPool.NewClass;
import ServerMessages.Messages;

/**
 *
 * @author victor
 */
public class AddCurrentAccount extends javax.swing.JFrame {

    private ResultSet rs;
   
    /**
     * Creates new form AddCurrentAccount
     */
    public AddCurrentAccount() {
        initComponents();
        NamesLabels();
    }
    
    private void NamesLabels(){
        try{
            String names = "SELECT name, surname, father_name FROM customer_list WHERE "
                    + "pin_id='"+LoadCustomer.getEgn()+"' ";
            //zarejdane na imenata na zaredeniq klient
            NewClass.Vrazka.pst = NewClass.Vrazka.con.prepareStatement(names);
            rs=NewClass.Vrazka.pst.executeQuery();
            
            // pokazvane na ekrana na imenata na zaredeniq klient
            while(rs.next()){
                String add1 = rs.getString("name");
                holderName.setText(add1);
                String add2 = rs.getString("surname");
                holderName2.setText(add2);
                String add3 = rs.getString("father_name");
                holderName3.setText(add3);
            }
        }catch(Exception ex){}
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        amount = new javax.swing.JLabel();
        currency = new javax.swing.JLabel();
        ibanField = new javax.swing.JTextField();
        accHolder = new javax.swing.JLabel();
        iban = new javax.swing.JLabel();
        amountField = new javax.swing.JTextField();
        holderName = new javax.swing.JLabel();
        currencyCombo = new javax.swing.JComboBox();
        accCancel = new javax.swing.JButton();
        save_acc = new javax.swing.JButton();
        holderName2 = new javax.swing.JLabel();
        holderName3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Добавяне на разплащателна сметка");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                enableMenu(evt);
            }
        });

        amount.setText("Сума: ");

        currency.setText("Валута: ");

        ibanField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ibanFieldActionPerformed(evt);
            }
        });

        accHolder.setText("Титуляр: ");

        iban.setText("IBAN: ");

        holderName.setText("----");

        currencyCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "BGN", "USA", "AUS", "EUR", "CAD", "GBP", "UAH", "SEK", "SNY", "CRC", "CUP", "XCD", "EGP", "FDJ", "HTG", "HDK", "VND", "TRY", "JPY", "KPW" }));

        accCancel.setText("Отказ");
        accCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accCancelActionPerformed(evt);
            }
        });

        save_acc.setText("Запази");
        save_acc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_accActionPerformed(evt);
            }
        });

        holderName2.setText("----");

        holderName3.setText("----");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(save_acc, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(accCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(accHolder)
                            .addComponent(amount)
                            .addComponent(iban)
                            .addComponent(currency))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(currencyCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(holderName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(holderName2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(holderName3))
                            .addComponent(ibanField)
                            .addComponent(amountField, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(accHolder)
                    .addComponent(holderName)
                    .addComponent(holderName2)
                    .addComponent(holderName3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ibanField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iban))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(currencyCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(currency))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(amountField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(amount))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 206, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(save_acc)
                    .addComponent(accCancel))
                .addGap(46, 46, 46))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ibanFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ibanFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ibanFieldActionPerformed

    private void accCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accCancelActionPerformed
        AddCurrentAccount.this.dispose();
    }//GEN-LAST:event_accCancelActionPerformed

    private void save_accActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_accActionPerformed
        try {
            String iban = ibanField.getText().trim();   // iban
            String currency = (String) currencyCombo.getSelectedItem(); // currency
            String amount = amountField.getText().trim(); // balance     

            String insert = "INSERT INTO account_type_current (iban_id, customer_list_id, balance,"
                    + " exchange_rate_id, employee_list_id_creator, creation_date,change_time,is_blocked) "
                    + "VALUES ('"+iban+"','" +LoadCustomer.getEgn()+ "','" + amount + "',"
                    + "'" + currency + "','"+LogIn.getEmployeeEgn()+"',SYSDATETIME(),SYSDATETIME(),'0') ";
            // vkarvane na vuvedenite danni za smetka v bazata danni 
            NewClass.Vrazka.st.execute(insert);
            Review_profile.Update_Current_Table();
            // zatvarqne na panela
            this.dispose();
            // aktivirane na zakluchenite butoni v glavniq panel
            Review_profile.jMenuBar1.setEnabled(true);
            Review_profile.closeAcc.setEnabled(true);
            Review_profile.Block.setEnabled(true);
            Review_profile.jButton2.setEnabled(true);
            Review_profile.jMenu2.setEnabled(true);
            Review_profile.jMenu1.setEnabled(true);
           
            // suobshtenie do servera za izvurshenata operaciq
            try {
                PrintWriter out = new PrintWriter(new OutputStreamWriter(Messages.Svurzvane.connection.getOutputStream()));
                out.println("employee: "+LogIn.getEmployeeID() +" created current account for "+LoadCustomer.getEgn()+".");
                out.flush();
            } catch (Exception ex) {
            }
            
             String history = "INSERT INTO employee_history (employee_username_id, action_description, "
                        + "action_time) VALUES ('"+LogIn.getEmployeeID()+"', "
                        + "'has created currency account for "+LoadCustomer.getEgn()+" ', SYSDATETIME()) ";
             // vuvejdane na danni za izvurshena operaciq v bazata danni
             NewClass.Vrazka.st.execute(history);
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_save_accActionPerformed

    private void enableMenu(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_enableMenu
        // aktivirane na butonite i menutata pri zatvarqne na panela
        Review_profile.jMenuBar1.setEnabled(true);
        Review_profile.closeAcc.setEnabled(true);
        Review_profile.Block.setEnabled(true);
        Review_profile.jButton2.setEnabled(true);
        Review_profile.jMenu2.setEnabled(true);
        Review_profile.jMenu1.setEnabled(true);
    }//GEN-LAST:event_enableMenu


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accCancel;
    private javax.swing.JLabel accHolder;
    private javax.swing.JLabel amount;
    private javax.swing.JTextField amountField;
    private javax.swing.JLabel currency;
    private javax.swing.JComboBox currencyCombo;
    private javax.swing.JLabel holderName;
    private javax.swing.JLabel holderName2;
    private javax.swing.JLabel holderName3;
    private javax.swing.JLabel iban;
    private javax.swing.JTextField ibanField;
    private javax.swing.JButton save_acc;
    // End of variables declaration//GEN-END:variables
}
