/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package banker.review;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Random;
import javax.swing.JOptionPane;
import org.apache.commons.codec.digest.DigestUtils;

import ConnectionPool.NewClass;
import ServerMessages.Messages;
import java.io.OutputStreamWriter;
import java.io.PrintWriter;

/**
 *
 * @author victor
 */
public class AddCustomerUserProfile extends javax.swing.JDialog {

    private ResultSet rs;
    /**
     * Creates new form AddCustomerUserProfile
     */
    public AddCustomerUserProfile() { 
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        regEgn = new javax.swing.JTextField();
        userIdField = new javax.swing.JTextField();
        passwordField = new javax.swing.JTextField();
        pinField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Създаване на потребителски профил");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                enableMenu(evt);
            }
        });

        jLabel1.setText("ЕГН:");

        jLabel2.setText("Потребителско име: ");

        jLabel3.setText("Парола: ");

        jLabel4.setText("ПИН: ");

        jButton1.setText("Регистрирай");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(146, 146, 146)
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(regEgn, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(55, 55, 55)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(userIdField, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                                .addComponent(passwordField)
                                .addComponent(pinField)))))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(regEgn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(userIdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(pinField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // promenlivi za dannite 
            String egn = regEgn.getText().trim();
            String userId = userIdField.getText().trim();
            String pass = DigestUtils.sha512Hex(passwordField.getText());

            String checkExisting = "SELECT * FROM customer_list WHERE pin_id = '" + egn + "' ";
            // proverka dali ima klient s tova egn v bazata 
            rs = NewClass.Vrazka.st.executeQuery(checkExisting);

            int count1 = 0;
            while (rs.next()) {
                count1 = count1 + 1;
            }
            if (count1 == 1) {
                String checkUsername = "SELECT * FROM customer_username WHERE username_id = '" + userId + "' ";
                // proverka dali ima klient s tozi username v bazata
                rs = NewClass.Vrazka.st.executeQuery(checkUsername);

                int count = 0;
                while (rs.next()) {
                    count = count + 1;
                }
                if (count == 1) {
                    JOptionPane.showMessageDialog(null, "Username is already taken! ");
                } else {
                    pinField.setEditable(false);
                    Random rn = new Random();

                    // generirane na pin
                    int randomPIN = (int) (Math.random() * 9000) + 1000;
                    pinField.setText("" + randomPIN);
                    String cryptPIN = DigestUtils.sha512Hex(pinField.getText());
                    JOptionPane.showMessageDialog(null, "Your PIN code is: " + randomPIN);

                    String registration = "INSERT INTO customer_username (customer_list_id, username_id,password,"
                            + "pin,change_time) VALUES "
                            + "('" + egn + "','" + userId + "','" + pass + "','" + cryptPIN + "',SYSDATETIME())";
                    // vuvejdane i suzdavane na potrebitelski profile v bazata 
                    NewClass.Vrazka.st.executeUpdate(registration);
                    // update na username v glavniq panel na zaredeniq klient
                    Review_profile.UsernameLabel();
                    
                    String history = "INSERT INTO employee_history (employee_username_id, action_description, "
                            + "action_time) VALUES ('" + LogIn.getEmployeeID() + "', "
                            + "'has registered user account for " + LoadCustomer.getEgn() + " ', SYSDATETIME()) ";
                    // vuvejdane na informaciq za napravenite promeni ot bankera v bazata danni
                    NewClass.Vrazka.st.execute(history);
                    // zatvarqne na panela
                    this.dispose();
                    // aktivirane na butonite v glavniq panel
                    Review_profile.jMenuBar1.setEnabled(true);
                    Review_profile.closeAcc.setEnabled(true);
                    Review_profile.Block.setEnabled(true);
                    Review_profile.jButton2.setEnabled(true);
                    Review_profile.jMenu2.setEnabled(true);
                    Review_profile.jMenu1.setEnabled(true);

                    // suobshtenie do server-a za izvurshenoto deistvie 
                    try {
                        PrintWriter out = new PrintWriter(new OutputStreamWriter(Messages.Svurzvane.connection.getOutputStream()));
                        out.println("employee: " + LogIn.getEmployeeID()+ " has registered a user.");
                        out.flush();
                    } catch (Exception ex) {
                    }
                }
            } else {
                JOptionPane.showMessageDialog(null, "You already have an account! ");
            }
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void enableMenu(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_enableMenu
        // aktivirane na butonite i menutata v glavniq prozorec pri zatvarqne na panela
        Review_profile.jMenuBar1.setEnabled(true);
        Review_profile.closeAcc.setEnabled(true);
        Review_profile.Block.setEnabled(true);
        Review_profile.jButton2.setEnabled(true);
        Review_profile.jMenu2.setEnabled(true);
        Review_profile.jMenu1.setEnabled(true);
    }//GEN-LAST:event_enableMenu

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField passwordField;
    private javax.swing.JTextField pinField;
    private javax.swing.JTextField regEgn;
    private javax.swing.JTextField userIdField;
    // End of variables declaration//GEN-END:variables
}
