/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package banker.review;

import java.io.OutputStreamWriter;
import java.io.PrintWriter;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;

import ConnectionPool.NewClass;
import ServerMessages.Messages;
import java.text.DateFormat;

/**
 *
 * @author victor
 */
public class AddDepositAccount extends javax.swing.JFrame {
   
    private ResultSet rs;
    
    /**
     * Creates new form AddAccount
     */
    public AddDepositAccount() {
        // izvikvane na metodi 
        initComponents();
        NamesLabels();
    }

    private void NamesLabels(){
        try{
            String names = "SELECT name, surname, father_name FROM customer_list WHERE "
                    + "pin_id='"+LoadCustomer.getEgn()+"' ";
            // izvlichane na imetana na zaredeniq klient po egn
            NewClass.Vrazka.pst = NewClass.Vrazka.con.prepareStatement(names);
            rs=NewClass.Vrazka.pst.executeQuery();

            while(rs.next()){
                // vizualizirane na imenata
                String add1 = rs.getString("name");
                holderName.setText(add1);
                String add2 = rs.getString("surname");
                holderName2.setText(add2);
                String add3 = rs.getString("father_name");
                holderName3.setText(add3);
            }
        }catch(Exception ex){}
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        accCancel = new javax.swing.JButton();
        save_acc = new javax.swing.JButton();
        currencyCombo = new javax.swing.JComboBox();
        accHolder = new javax.swing.JLabel();
        iban = new javax.swing.JLabel();
        ibanField = new javax.swing.JTextField();
        currency = new javax.swing.JLabel();
        holderName = new javax.swing.JLabel();
        deposit = new javax.swing.JLabel();
        depositField = new javax.swing.JTextField();
        interestRateField = new javax.swing.JTextField();
        interestRate = new javax.swing.JLabel();
        holderName2 = new javax.swing.JLabel();
        holderName3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        depositDeadLine = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Довавяна на депозитна сметка");
        setLocation(new java.awt.Point(750, 120));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                enableMenu(evt);
            }
        });

        accCancel.setText("Отказ");
        accCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accCancelActionPerformed(evt);
            }
        });

        save_acc.setText("Запази");
        save_acc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_accActionPerformed(evt);
            }
        });

        currencyCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "BGN", "USA", "AUS", "EUR", "CAD", "GBP", "UAH", "SEK", "SNY", "CRC", "CUP", "XCD", "EGP", "FDJ", "HTG", "HDK", "VND", "TRY", "JPY", "KPW" }));

        accHolder.setText("Титуляр: ");

        iban.setText("IBAN: ");

        ibanField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ibanFieldActionPerformed(evt);
            }
        });

        currency.setText("Валута: ");

        holderName.setText("---");

        deposit.setText("Депозит:");

        depositField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depositFieldActionPerformed(evt);
            }
        });

        interestRate.setText("Лихвен процент:");

        holderName2.setText("---");

        holderName3.setText("---");

        jLabel1.setText("Срок на депозита: ");

        depositDeadLine.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6 ", "7", "8", "9", "10" }));

        jLabel2.setText("години");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(save_acc, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(accCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(101, 101, 101)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(accHolder)
                                .addComponent(iban)
                                .addComponent(deposit)
                                .addComponent(currency))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(currencyCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ibanField)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(holderName)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(holderName2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(holderName3))
                                .addComponent(depositField, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(1, 1, 1))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(54, 54, 54)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(interestRate)
                                .addComponent(jLabel1))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(interestRateField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(depositDeadLine, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel2)))
                            .addGap(2, 2, 2))))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(accHolder)
                    .addComponent(holderName)
                    .addComponent(holderName2)
                    .addComponent(holderName3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ibanField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iban))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(depositField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deposit))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(currencyCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(currency))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(interestRateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(interestRate))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(depositDeadLine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(save_acc)
                    .addComponent(accCancel))
                .addGap(23, 23, 23))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ibanFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ibanFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ibanFieldActionPerformed

    private void accCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accCancelActionPerformed
        AddDepositAccount.this.dispose();
    }//GEN-LAST:event_accCancelActionPerformed

    private void save_accActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_accActionPerformed
        try{
            // promenlivi za vuvedenite danni 
            String iban = ibanField.getText().trim();
            String currency = (String)currencyCombo.getSelectedItem();
            String deposit = depositField.getText().trim();
            String interestRate = interestRateField.getText().trim();
            DateFormat dateFormat = new SimpleDateFormat("yyyy");
            Date date = new Date();
            int buff = Integer.parseInt(dateFormat.format(date));
            buff+=Integer.parseInt(depositDeadLine.getSelectedItem().toString());
            DateFormat dateFormat2 = new SimpleDateFormat("MM-dd");
            Date depositDate = new Date();
            String unblock_date = buff+"-"+dateFormat2.format(depositDate);
            Date d = new Date();
            SimpleDateFormat ft = new SimpleDateFormat ("yyyy-MM-dd");
                d.setTime(d.getTime() + 31L * 24 * 60 * 60 * 1000);
                String nextDate = ft.format(d);
            
            String insert = "INSERT INTO account_type_deposit (iban_id,customer_list_id,deposit_amount,"
                    + "interest_rate,next_accumulation_date,exchange_rate_id,"
                    + "unblock_date,employee_list_id_creator,creation_date,change_time,is_locked,is_blocked) "
                    + "VALUES ('"+iban+"','"+LoadCustomer.getEgn()+"','"+deposit+"',"
                    + "'"+interestRate+"','"+nextDate+"','"+currency+"','"+unblock_date+"','"+LogIn.getEmployeeEgn()+"',"
                    + "SYSDATETIME(),SYSDATETIME(),'1','0') ";
            // vuvejdane i suzdavane na smetka za zaredeniq klient 
            NewClass.Vrazka.st.executeUpdate(insert);
            
            // update na tablicata za depozitni smetki v glavniq panel
            Review_profile.Update_Deposit_table();
            
            // zatvarqne na prozoreca
            this.dispose();
            
            // suobshtenie do server-a za izvurshenoto deistvie 
            try {
                PrintWriter out = new PrintWriter(new OutputStreamWriter(Messages.Svurzvane.connection.getOutputStream()));
                out.println("employee: "+LogIn.getEmployeeID() +" created deposit account for "+LoadCustomer.getEgn()+".");
                out.flush();
            } catch (Exception ex) {
            }
            
            
            String history = "INSERT INTO employee_history (employee_username_id, action_description, "
                        + "action_time) VALUES ('"+LogIn.getEmployeeID()+"', "
                        + "'has created deposit account for "+LoadCustomer.getEgn()+" ', SYSDATETIME()) ";
            // vuvejdane na danni za izvurshenoto deistvie v bazata
                NewClass.Vrazka.st.execute(history);
        }catch(Exception ex){
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_save_accActionPerformed

    private void depositFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_depositFieldActionPerformed

    private void enableMenu(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_enableMenu
        // aktivirane na menuttata i butonite v glavniq prozorec sled zatvarqneto na tozi panel 
        Review_profile.jMenuBar1.setEnabled(true);
        Review_profile.closeAcc.setEnabled(true);
        Review_profile.Block.setEnabled(true);
        Review_profile.jButton2.setEnabled(true);
        Review_profile.jMenu2.setEnabled(true);
        Review_profile.jMenu1.setEnabled(true);
    }//GEN-LAST:event_enableMenu



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accCancel;
    private javax.swing.JLabel accHolder;
    private javax.swing.JLabel currency;
    private javax.swing.JComboBox currencyCombo;
    private javax.swing.JLabel deposit;
    private javax.swing.JComboBox depositDeadLine;
    private javax.swing.JTextField depositField;
    private javax.swing.JLabel holderName;
    private javax.swing.JLabel holderName2;
    private javax.swing.JLabel holderName3;
    private javax.swing.JLabel iban;
    private javax.swing.JTextField ibanField;
    private javax.swing.JLabel interestRate;
    private javax.swing.JTextField interestRateField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton save_acc;
    // End of variables declaration//GEN-END:variables
}
