/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package banker.review;

import java.io.OutputStreamWriter;
import java.io.PrintWriter;
import java.sql.ResultSet;

import ConnectionPool.NewClass;
import ServerMessages.Messages;

/**
 *
 * @author victor
 */
public class AddSavingAccount extends javax.swing.JFrame {

    private ResultSet rs;
    
    /**
     * Creates new form AddSavingAccount
     */
    public AddSavingAccount() {
        // izvikvane na metodi 
        initComponents();
        NamesLabels();
    }

    private void NamesLabels(){
        try{
            String names = "SELECT name, surname, father_name FROM customer_list WHERE "
                    + "pin_id='"+LoadCustomer.getEgn()+"' ";
            // vzemane na imenata na zaredeniq klient ot bazata
            NewClass.Vrazka.pst = NewClass.Vrazka.con.prepareStatement(names);
            rs=NewClass.Vrazka.pst.executeQuery();

            while(rs.next()){
                // vizualizirane na imenata
                String add1 = rs.getString("name");
                holderName.setText(add1);
                String add2 = rs.getString("surname");
                holderName2.setText(add2);
                String add3 = rs.getString("father_name");
                holderName3.setText(add3);
            }
        }catch(Exception ex){}
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        accCancel = new javax.swing.JButton();
        save_acc = new javax.swing.JButton();
        holderName = new javax.swing.JLabel();
        currencyCombo = new javax.swing.JComboBox();
        iban = new javax.swing.JLabel();
        amount = new javax.swing.JLabel();
        amountField = new javax.swing.JTextField();
        ibanField = new javax.swing.JTextField();
        accHolder = new javax.swing.JLabel();
        currency = new javax.swing.JLabel();
        holderName2 = new javax.swing.JLabel();
        holderName3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Добавяне на спестовна сметка");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                enableMenu(evt);
            }
        });

        accCancel.setText("Отказ");
        accCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accCancelActionPerformed(evt);
            }
        });

        save_acc.setText("Запази");
        save_acc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_accActionPerformed(evt);
            }
        });

        holderName.setText("---");

        currencyCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "BGN", "USA", "AUS", "EUR", "CAD", "GBP", "UAH", "SEK", "SNY", "CRC", "CUP", "XCD", "EGP", "FDJ", "HTG", "HDK", "VND", "TRY", "JPY", "KPW" }));

        iban.setText("IBAN: ");

        amount.setText("Сума: ");

        ibanField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ibanFieldActionPerformed(evt);
            }
        });

        accHolder.setText("Титуляр: ");

        currency.setText("Валута: ");

        holderName2.setText("---");

        holderName3.setText("---");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(save_acc, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(accCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(accHolder)
                            .addComponent(amount)
                            .addComponent(iban)
                            .addComponent(currency))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(currencyCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(holderName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(holderName2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(holderName3))
                            .addComponent(ibanField)
                            .addComponent(amountField, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(accHolder)
                    .addComponent(holderName)
                    .addComponent(holderName2)
                    .addComponent(holderName3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ibanField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iban))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(currencyCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(currency))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(amountField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(amount))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 229, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(save_acc)
                    .addComponent(accCancel))
                .addGap(32, 32, 32))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void accCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accCancelActionPerformed
        AddSavingAccount.this.dispose();
    }//GEN-LAST:event_accCancelActionPerformed

    private void save_accActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_accActionPerformed
        try{
            // promenlivi za vuvedenite danni
            String iban = ibanField.getText().trim();
            String currency = (String)currencyCombo.getSelectedItem();
            String amount = amountField.getText().trim();
            
            String insert = "INSERT INTO account_type_saving (iban_id, customer_list_id, balance,"
                    + " exchange_rate_id, employee_list_id_creator, creation_date,change_time,is_blocked) "
            + "VALUES ('"+iban+"','"+LoadCustomer.getEgn()+"','"+amount+"','"+currency+"',"
                    + "'"+LogIn.getEmployeeEgn()+"',SYSDATETIME(),SYSDATETIME(),'0') ";
            // vuvejdane i suzdavane na smetka v bazata danni
            NewClass.Vrazka.st.execute(insert);
            // update na tablicata za spestovni smetki
            Review_profile.Update_Saving_table();
            // zatvarqne na panela
            this.dispose();
            
            // suobshtenie do server-a za izvurshenoto deistvie
            try {
                PrintWriter out = new PrintWriter(new OutputStreamWriter(Messages.Svurzvane.connection.getOutputStream()));
                out.println("employee: "+LogIn.getEmployeeID() +" created saving account for "+LoadCustomer.getEgn()+".");
                out.flush();
            } catch (Exception ex) {
            }
            
            String history = "INSERT INTO employee_history (employee_username_id, action_description, "
                        + "action_time) VALUES ('"+LogIn.getEmployeeID()+"', "
                        + "'has created saving account for "+LoadCustomer.getEgn()+" ', SYSDATETIME()) ";
            // vuvedjdane na danni za izvurshenoto ot bankera deistvie v bazata danni
            NewClass.Vrazka.st.execute(history);
        }catch(Exception ex){
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_save_accActionPerformed

    private void ibanFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ibanFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ibanFieldActionPerformed

    private void enableMenu(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_enableMenu
        // aktivirane na butoni i menuta v glaniq panel sled zatvarqne na tekushtiq 
        Review_profile.jMenuBar1.setEnabled(true);
        Review_profile.closeAcc.setEnabled(true);
        Review_profile.Block.setEnabled(true);
        Review_profile.jButton2.setEnabled(true);
        Review_profile.jMenu2.setEnabled(true);
        Review_profile.jMenu1.setEnabled(true);
    }//GEN-LAST:event_enableMenu


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accCancel;
    private javax.swing.JLabel accHolder;
    private javax.swing.JLabel amount;
    private javax.swing.JTextField amountField;
    private javax.swing.JLabel currency;
    private javax.swing.JComboBox currencyCombo;
    private javax.swing.JLabel holderName;
    private javax.swing.JLabel holderName2;
    private javax.swing.JLabel holderName3;
    private javax.swing.JLabel iban;
    private javax.swing.JTextField ibanField;
    private javax.swing.JButton save_acc;
    // End of variables declaration//GEN-END:variables
}
