/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package banker.review;

import ConnectionPool.NewClass;
import java.sql.ResultSet;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author victor
 */
public class CustomerActionsTest extends javax.swing.JFrame {

    private ResultSet rs;
    /**
     * Creates new form CustomerActionsTest
     */
    public CustomerActionsTest() {
        initComponents();
        NamesLabels();
        Update_Table();
    }
    
    public void NamesLabels(){
        try{
            String names = "SELECT name, surname, father_name FROM customer_list WHERE "
                    + "pin_id='"+LoadCustomer.getEgn()+"' ";
            // vzemane na danni ot bazata danni
            NewClass.Vrazka.pst = NewClass.Vrazka.con.prepareStatement(names);
            rs=NewClass.Vrazka.pst.executeQuery();

            while(rs.next()){
                // vizualizirane na dannite za imenata na zaredeniq klient
                String add1 = rs.getString("name");
                customerLbl.setText(add1);
                String add2 = rs.getString("surname");
                customerLbl2.setText(add2);
                String add3 = rs.getString("father_name");
                customerLbl3.setText(add3);
            }
            rs.close();
            
            String history = "INSERT INTO employee_history (employee_username_id, action_description, "
                    + "action_time) VALUES ('" + LogIn.getEmployeeID() + "', "
                    + "'has opened customer action of: "+LoadCustomer.getEgn()+" ', SYSDATETIME()) ";
            // vubejdane na danni za izvurshenoto deistvie ot bankera v bazata danni
            NewClass.Vrazka.st.execute(history); 
        }catch(Exception ex){}
    }
    
    private void Update_Table(){
        try{
            String customerUsername;
            
            String username = "SELECT username_id FROM customer_username WHERE customer_list_id='"+LoadCustomer.getEgn()+"'";
            // vzemane na potrebitelskoto na klienta 
            rs = NewClass.Vrazka.st.executeQuery(username);
            rs.next();
            customerUsername = rs.getString("username_id");
            rs.close(); 
  
            String sql = "SELECT action_id as 'номер', customer_username_id as 'потребителско име',"
                    + " action_description as 'описание', action_time as 'дата на извършване'"
                    + " FROM customer_history WHERE customer_username_id='"+customerUsername+"' ";
            // vzemane na dannite ot bazata za tova potrebitelsko ime
            NewClass.Vrazka.pst = NewClass.Vrazka.con.prepareStatement(sql);
            rs=NewClass.Vrazka.pst.executeQuery();
            // vuvejdane na vzetite danni v tablicata
            customerActions.setModel(DbUtils.resultSetToTableModel(rs));
            
        }catch(Exception ex){
            System.out.println(ex.getMessage());
        }  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        customerActions = new javax.swing.JTable();
        customerLbl = new javax.swing.JLabel();
        customerLbl2 = new javax.swing.JLabel();
        customerLbl3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Действия на потребителя");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                enableMenu(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        customerActions.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(customerActions);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 628, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        customerLbl.setText("jLabel2");

        customerLbl2.setText("jLabel2");

        customerLbl3.setText("jLabel2");

        jLabel1.setText("Потребител:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(199, 199, 199)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(customerLbl)
                .addGap(18, 18, 18)
                .addComponent(customerLbl2)
                .addGap(18, 18, 18)
                .addComponent(customerLbl3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customerLbl)
                    .addComponent(customerLbl2)
                    .addComponent(customerLbl3)
                    .addComponent(jLabel1))
                .addGap(38, 38, 38)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void enableMenu(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_enableMenu
        // aktivirane na butonite i menutata v glavniq panel sled zatvarqneto na tozi 
        Review_profile.jMenuBar1.setEnabled(true);
        Review_profile.closeAcc.setEnabled(true);
        Review_profile.Block.setEnabled(true);
        Review_profile.jButton2.setEnabled(true);
        Review_profile.jMenu2.setEnabled(true);
        Review_profile.jMenu1.setEnabled(true);
    }//GEN-LAST:event_enableMenu



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable customerActions;
    private javax.swing.JLabel customerLbl;
    private javax.swing.JLabel customerLbl2;
    private javax.swing.JLabel customerLbl3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
