/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package banker.review;

import ConnectionPool.NewClass;
import ServerMessages.Messages;
import java.io.OutputStreamWriter;
import java.io.PrintWriter;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author victor
 */
public class CustomerInfo extends javax.swing.JFrame {
   
    private ResultSet rs;
    private static String mail;
    /**
     * Creates new form CustomerInfo
     */
    public CustomerInfo() {
        initComponents();
        NameLabels();
    }
    
    // getters and setters za mail 
    public static void setMail(String mail){
        CustomerInfo.mail=mail;
    }

    public static String getMail(){
        return CustomerInfo.mail;
    }
    
    public void NameLabels(){
        try{
            String names = "SELECT name, surname, father_name, pin_id, sex,nationality, birth_date, "
                    + "document_issue_date, document_expiry_date, document_number, birth_place, residence,"
                    + "document_authority, zip_code, email, phone_number FROM customer_list WHERE "
                    + "pin_id='"+LoadCustomer.getEgn()+"' ";
            // vzemane na dannite ot bazata danni za zaredeniq klient
            NewClass.Vrazka.pst = NewClass.Vrazka.con.prepareStatement(names);
            rs=NewClass.Vrazka.pst.executeQuery();

            while(rs.next()){
                // vizualiziraneto im 
                String add1 =rs.getString("pin_id");
                egnLbl.setText(add1);
                String add2 = rs.getString("name");
                nameLbl.setText(add2);
                String add3 = rs.getString("surname");
                surnameLbl.setText(add3);
                String add4 = rs.getString("father_name");
                fathersNameLbl.setText(add4);
                String add5 = rs.getString("sex");
                sexLbl.setText(add5);
                String add6 = rs.getString("nationality");
                nationalityLbl.setText(add6);
                nationalityLbl2.setText(add6);
                String add7 = rs.getString("birth_date");
                birthDateLbl.setText(add7);
                String add8 = rs.getString("document_issue_date");
                issueIdLbl.setText(add8);
                String add9 = rs.getString("document_expiry_date");
                expiryIdLbl.setText(add9);
                String add10 = rs.getString("document_number");
                idNumLbl.setText(add10);
                String add11 = rs.getString("birth_place");
                placeOfBirthLbl.setText(add11);
                String add12 = rs.getString("residence");
                addressLbl.setText(add12);
                String add13 = rs.getString("document_authority");
                authorityIdLbl.setText(add13);
                String add14 = rs.getString("zip_code");
                zipField.setText(add14);
                String add15 = rs.getString("phone_number");
                phoneField.setText(add15);
                String add16 = rs.getString("email");
                emailField.setText(add16);
            }
            rs.close();
        }catch(Exception ex){}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        egn = new javax.swing.JLabel();
        firstName = new javax.swing.JLabel();
        middleName = new javax.swing.JLabel();
        lastName = new javax.swing.JLabel();
        dateOfBirth = new javax.swing.JLabel();
        sex = new javax.swing.JLabel();
        state = new javax.swing.JLabel();
        city = new javax.swing.JLabel();
        address = new javax.swing.JLabel();
        idNum = new javax.swing.JLabel();
        dateOfDocIssue = new javax.swing.JLabel();
        idValidy = new javax.swing.JLabel();
        placeOfBirth = new javax.swing.JLabel();
        docAuthority = new javax.swing.JLabel();
        nationality = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        phone = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        zip = new javax.swing.JLabel();
        zipField = new javax.swing.JTextField();
        emailField = new javax.swing.JTextField();
        phoneField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        egnLbl = new javax.swing.JLabel();
        nameLbl = new javax.swing.JLabel();
        surnameLbl = new javax.swing.JLabel();
        fathersNameLbl = new javax.swing.JLabel();
        birthDateLbl = new javax.swing.JLabel();
        sexLbl = new javax.swing.JLabel();
        nationalityLbl = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        addressLbl = new javax.swing.JLabel();
        idNumLbl = new javax.swing.JLabel();
        issueIdLbl = new javax.swing.JLabel();
        expiryIdLbl = new javax.swing.JLabel();
        placeOfBirthLbl = new javax.swing.JLabel();
        authorityIdLbl = new javax.swing.JLabel();
        nationalityLbl2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Преглед на потребителски данни");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                enableMenu(evt);
            }
        });

        egn.setText("ЕГН: ");

        firstName.setText("Име: ");

        middleName.setText("Презиме: ");

        lastName.setText("Фамилия: ");

        dateOfBirth.setText("Дата на раждане: ");

        sex.setText("Пол: ");

        state.setText("Държава: ");

        city.setText("Град: ");

        address.setText("Адрес: ");

        idNum.setText("Номер на лична карта: ");

        dateOfDocIssue.setText("Дата на издаване: ");

        idValidy.setText("Дата на валидност на лична карта: ");

        placeOfBirth.setText("Място на раждане:");

        docAuthority.setText("Автор на документа: ");

        nationality.setText("Националност: ");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        phone.setText("Телефонен номер: ");

        email.setText("Емейл: ");

        zip.setText("ZIP: ");

        jButton1.setText("Промени");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(email)
                                .addGap(6, 6, 6)
                                .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(phone)
                                .addGap(6, 6, 6)
                                .addComponent(phoneField, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(zip)
                        .addGap(6, 6, 6)
                        .addComponent(zipField, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(249, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phone)
                    .addComponent(phoneField, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(email))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(zipField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(zip))
                .addGap(16, 16, 16)
                .addComponent(jButton1)
                .addContainerGap())
        );

        egnLbl.setText("Празно");

        nameLbl.setText("Празно");

        surnameLbl.setText("Празно");

        fathersNameLbl.setText("Празно");

        birthDateLbl.setText("Празно");

        sexLbl.setText("Празно");

        nationalityLbl.setText("Празно");

        jLabel8.setText("Празно");

        addressLbl.setText("Празно");

        idNumLbl.setText("Празно");

        issueIdLbl.setText("Празно");

        expiryIdLbl.setText("Празно");

        placeOfBirthLbl.setText("Празно");

        authorityIdLbl.setText("Празно");

        nationalityLbl2.setText("Празно");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(egn)
                        .addGap(6, 6, 6)
                        .addComponent(egnLbl)
                        .addGap(163, 163, 163)
                        .addComponent(idNum)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(idNumLbl))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(firstName)
                        .addGap(6, 6, 6)
                        .addComponent(nameLbl)
                        .addGap(189, 189, 189)
                        .addComponent(dateOfDocIssue)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(issueIdLbl))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(state)
                        .addGap(6, 6, 6)
                        .addComponent(nationalityLbl))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(city)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(address)
                        .addGap(6, 6, 6)
                        .addComponent(addressLbl))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(141, 141, 141)
                            .addComponent(sex)
                            .addGap(6, 6, 6)
                            .addComponent(sexLbl)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nationality)
                            .addGap(6, 6, 6)
                            .addComponent(nationalityLbl2))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(71, 71, 71)
                            .addComponent(dateOfBirth)
                            .addGap(6, 6, 6)
                            .addComponent(birthDateLbl)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(docAuthority)
                            .addGap(6, 6, 6)
                            .addComponent(authorityIdLbl))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(115, 115, 115)
                            .addComponent(middleName)
                            .addGap(6, 6, 6)
                            .addComponent(surnameLbl)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(idValidy)
                            .addGap(6, 6, 6)
                            .addComponent(expiryIdLbl))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(114, 114, 114)
                            .addComponent(lastName)
                            .addGap(6, 6, 6)
                            .addComponent(fathersNameLbl)
                            .addGap(188, 188, 188)
                            .addComponent(placeOfBirth)
                            .addGap(6, 6, 6)
                            .addComponent(placeOfBirthLbl))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(egn)
                    .addComponent(egnLbl)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(idNumLbl)
                        .addComponent(idNum)))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(firstName)
                    .addComponent(nameLbl)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(issueIdLbl)
                        .addComponent(dateOfDocIssue)))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(middleName)
                    .addComponent(surnameLbl)
                    .addComponent(idValidy)
                    .addComponent(expiryIdLbl))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lastName)
                    .addComponent(fathersNameLbl)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(placeOfBirthLbl)
                        .addComponent(placeOfBirth)))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateOfBirth)
                    .addComponent(birthDateLbl)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(authorityIdLbl)
                        .addComponent(docAuthority)))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sex)
                    .addComponent(sexLbl)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nationalityLbl2)
                        .addComponent(nationality)))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(state)
                    .addComponent(nationalityLbl))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(city)
                    .addComponent(jLabel8))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(address)
                    .addComponent(addressLbl))
                .addGap(26, 26, 26)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // promenlivi za vuvedeni novi danni 
            String phone = phoneField.getText().trim();
            String mail = emailField.getText().trim();
            String zip = zipField.getText().trim();
            CustomerInfo.setMail(mail);

            UsernameCheck usernameCheck = new UsernameCheck(CustomerInfo.getMail());
            // proverka dali mail-a e validen
            if (usernameCheck.isValid()) {
                String update = "UPDATE customer_list SET zip_code='" + zip + "' , email='" + mail + "' , "
                        + "phone_number='" + phone + "' WHERE pin_id='" + LoadCustomer.getEgn() + "' ";
                // update na dannite v bazata danni
                NewClass.Vrazka.st.executeUpdate(update);
                // suobshtenie za bankera che operaciqta e preminala uspeshno 
                JOptionPane.showMessageDialog(null, "Changed! ");
                               
                String history = "INSERT INTO employee_history (employee_username_id, action_description, "
                        + "action_time) VALUES ('" + LogIn.getEmployeeID() + "', "
                        + "'has changed phone, email and zip of: " + LoadCustomer.getEgn() + " . ', SYSDATETIME()) ";
                //  vuvejdane na danni za izvurshenoto deistvie ot bankera v bazata danni 
                NewClass.Vrazka.st.execute(history);

                // suobshtenie do server-a za izvurshenoto deistvie 
                try {
                    PrintWriter out = new PrintWriter(new OutputStreamWriter(Messages.Svurzvane.connection.getOutputStream()));
                    out.println("employee: " + LogIn.getEmployeeID() + " has changed phone, email amd zip of: " + LoadCustomer.getEgn() + ".");
                    out.flush();
                } catch (Exception ex) {
                }
            } else {
                JOptionPane.showMessageDialog(null, "Incorrect format! ");
            }
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void enableMenu(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_enableMenu
        // aktivirane na butoni i menuta v glavniq panels sled zatvarqneto na tozi 
        Review_profile.jMenuBar1.setEnabled(true);
        Review_profile.closeAcc.setEnabled(true);
        Review_profile.Block.setEnabled(true);
        Review_profile.jButton2.setEnabled(true);
        Review_profile.jMenu2.setEnabled(true);
        Review_profile.jMenu1.setEnabled(true);
    }//GEN-LAST:event_enableMenu

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel address;
    private javax.swing.JLabel addressLbl;
    private javax.swing.JLabel authorityIdLbl;
    private javax.swing.JLabel birthDateLbl;
    private javax.swing.JLabel city;
    private javax.swing.JLabel dateOfBirth;
    private javax.swing.JLabel dateOfDocIssue;
    private javax.swing.JLabel docAuthority;
    private javax.swing.JLabel egn;
    private javax.swing.JLabel egnLbl;
    private javax.swing.JLabel email;
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel expiryIdLbl;
    private javax.swing.JLabel fathersNameLbl;
    private javax.swing.JLabel firstName;
    private javax.swing.JLabel idNum;
    private javax.swing.JLabel idNumLbl;
    private javax.swing.JLabel idValidy;
    private javax.swing.JLabel issueIdLbl;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lastName;
    private javax.swing.JLabel middleName;
    private javax.swing.JLabel nameLbl;
    private javax.swing.JLabel nationality;
    private javax.swing.JLabel nationalityLbl;
    private javax.swing.JLabel nationalityLbl2;
    private javax.swing.JLabel phone;
    private javax.swing.JTextField phoneField;
    private javax.swing.JLabel placeOfBirth;
    private javax.swing.JLabel placeOfBirthLbl;
    private javax.swing.JLabel sex;
    private javax.swing.JLabel sexLbl;
    private javax.swing.JLabel state;
    private javax.swing.JLabel surnameLbl;
    private javax.swing.JLabel zip;
    private javax.swing.JTextField zipField;
    // End of variables declaration//GEN-END:variables
}
