/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package banker.review;

import ConnectionPool.NewClass;
import java.sql.ResultSet;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author victor
 */
public class HistoryTest extends javax.swing.JFrame {

    private ResultSet rs;
    /**
     * Creates new form HistoryTest
     */
    public HistoryTest() {
        initComponents();
        NamesLabels();
        Update_Table();
    }
    
    private void NamesLabels(){
        try{
            String names = "SELECT name, surname, father_name FROM employee_list WHERE "
                    + "pin_id='"+LogIn.getEmployeeEgn()+"' ";
            // vzemane na danni ot bazata danni 
            NewClass.Vrazka.pst = NewClass.Vrazka.con.prepareStatement(names);
            rs=NewClass.Vrazka.pst.executeQuery();

            while(rs.next()){
                // vizualizirane na dannite s imenata na lognatiq banker
                String add1 = rs.getString("name");
                name1.setText(add1);
                String add2 = rs.getString("surname");
                name2.setText(add2);
                String add3 = rs.getString("father_name");
                name3.setText(add3);
            }
        }catch(Exception ex){}
    }
    
    private void Update_Table(){
        try {
            String table = "SELECT action_id as 'номер', employee_username_id as 'име', action_description as 'действие', "
                    + " action_time as 'дата на извършване' FROM employee_history "
                    + "WHERE employee_username_id='" + LogIn.getEmployeeID() + "' ";
            // vzimane na dannite ot bazata danni 
            NewClass.Vrazka.pst = NewClass.Vrazka.con.prepareStatement(table);
            rs = NewClass.Vrazka.pst.executeQuery();
            // slagane na vzetite danni v tablicata
            historyTest.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception ex) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        historyTest = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        name1 = new javax.swing.JLabel();
        name2 = new javax.swing.JLabel();
        name3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("История");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                enableMenu(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Действия: "));

        historyTest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(historyTest);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel1.setText("Име: ");

        jLabel2.setText("Презиме: ");

        jLabel3.setText("Фамилия: ");

        name1.setText("Празно");

        name2.setText("Празно");

        name3.setText("Празно");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(name1)
                            .addComponent(name2)
                            .addComponent(name3))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(name1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(name2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(name3))
                .addGap(40, 40, 40)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void enableMenu(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_enableMenu
//        if(LoadCustomer.getEgn().equals("null")){
//            Review_profile.jMenuItem18.setEnabled(false);
//            Review_profile.changeUsername.setEnabled(false);
//            Review_profile.jMenuItem20.setEnabled(false);
//            Review_profile.jMenu6.setEnabled(false);
//            Review_profile.jMenuItem9.setEnabled(false);
//            Review_profile.jMenuItem5.setEnabled(false);
//            Review_profile.jMenuItem10.setEnabled(false);
//            Review_profile.jMenuItem11.setEnabled(false);
//            Review_profile.jMenuItem22.setEnabled(false);
//            Review_profile.jMenuItem24.setEnabled(false);
//            Review_profile.closeAcc.setEnabled(false);
//            Review_profile.Block.setEnabled(false);
//            Review_profile.jButton2.setEnabled(false);
//        } else {
            Review_profile.jMenuBar1.setEnabled(true);
            Review_profile.closeAcc.setEnabled(true);
            Review_profile.Block.setEnabled(true);
            Review_profile.jButton2.setEnabled(true);
            Review_profile.jMenu2.setEnabled(true);
            Review_profile.jMenu1.setEnabled(true);
   //     }
    }//GEN-LAST:event_enableMenu



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable historyTest;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel name1;
    private javax.swing.JLabel name2;
    private javax.swing.JLabel name3;
    // End of variables declaration//GEN-END:variables
}
